### ISSUE TITLE
How can I use this?

### ISSUE THREAD

**Issue by dillfrescott** [IAHispano/Audio-Upscaler#2]
There are little to no instructions.

**Comment by dillfrescott** [comment]
I'm pretty sure it works nearly the exact same as https://github.com/haoheliu/versatile_audio_super_resolution/ but it was just changed to work with the applio voice conversion software.

**Comment by FlexTestHD** [comment]
Oh, thanks for the tip! I got the original to work (I only have the problem that the output is slowed down and lower pitched for some reason). I'll give the project a try in the next few days, the longer input definitely sounds useful, so thanks for the response! :)

**Comment by dillfrescott** [comment]
If its changed pitch and length that means the sampling rates are mismatched.

**Comment by Nick088Official** [comment]
> If its changed pitch and length that means the sampling rates are mismatched.

At the end we found out that the problem is only the Gradio UI demo having this problem weirdly
